# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique_for_date='reg_date')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roomie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('agreement', models.CharField(max_length=1000)),
                ('photo1', models.ImageField(upload_to='roomies/%Y/%m/%d')),
                ('photo2', models.ImageField(upload_to='roomies/%Y/%m/%d')),
                ('photo3', models.ImageField(upload_to='roomies/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='roomies/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='roomies/%Y/%m/%d')),
                ('payment', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique_for_date='reg_date')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Roommate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
