# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 19:08
from __future__ import unicode_literals

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180921_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
